flyway:
  enabled: true
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_demo_development?autoReconnect=true&useSSL=false
    username: spring.boot.demo
    password:
server:
  port: 8080