CREATE TABLE devices (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY UK_uuid (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;